@startuml
hide circle

BeReferralPrescription <|-- BeNursingPrescription
BeReferralPrescription <|-- BeDiagnosticImagingPrescription	
BeReferralPrescription <|-- BeLaboratoryPrescription
BeReferralPrescription <|-- BePhysiotherapyPrescription

BeNursingPrescription <|-- BeNursingPrescriptionBladderCare
BeNursingPrescription <|-- BeNursingPrescriptionDigestiveSystemCare
BeReferralPrescriptionGroup --> BeReferralPrescription : contains inline

class BeReferralPrescriptionGroup {
  |_UHMEP identifier
  |_BeReferralPrescription[] prescriptions
}

class BeNursingPrescriptionBladderCare{
  |_BladderCare orderDetail
  
}
class BeNursingPrescriptionDigestiveSystemCare{
  |_DigestiveSystemCare orderDetail
}
@enduml