@startuml
BeReferralPrescription <|-- BeNursingPrescription
BeReferralPrescription <|-- BeDiagnosticImagingPrescription	
BeReferralPrescription <|-- BeLaboratoryPrescription
BeReferralPrescription <|-- BePhysiotherapyPrescription

BeNursingPrescription <|-- BeNursingPrescriptionBladderCare
BeReferralPrescriptionGroup --> BeReferralPrescription : contains inline

BeReferralPrescriptionGroup : UHMEP identifier
BeReferralPrescriptionGroup : BeReferralPrescription[] prescriptions



@enduml
