@startuml
'skinparam linetype ortho
skinparam linetype polyline
hide circle
hide stereotype

'!pragma layout smetana

skinparam class<<MD>> {
 BorderColor DarkSlateGray
 BackgroundColor WhiteSmoke
 HeaderBackgroundColor #909090
}

skinparam class<<TM>> {
 BorderColor #505090
 BackgroundColor APPLICATION
 HeaderBackgroundColor SkyBlue
}

'[Add your PlantUML diagram here showing the data model for notifications]
'Example structure:
'    class "**ServiceRequest**" as SR<<TM>> {
'        |_ resultReceiver 0..*
'    }

@enduml
