@startuml
[*] --> ServiceRequest.status.draft
ServiceRequest.status.draft --> ServiceRequest.status.active
ServiceRequest.status.draft --> ServiceRequest.status.enteredinerror
ServiceRequest.status.active --> ServiceRequest.status.revoked
ServiceRequest.status.revoked --> [*]
ServiceRequest.status.enteredinerror--> [*]
ServiceRequest.status.completed --> [*]
ServiceRequest.status.draft : Registratie
ServiceRequest.status.completed : [uitgevoerd]


state ServiceRequest.status.active {
  Task.status.ready : Open
  Task.status.inprogress : In Uitvoering
  Task.status.failed : Vervallen

  Task.status.ready --> Task.status.inprogress
  Task.status.ready --> Task.status.failed
  Task.status.inprogress --> ServiceRequest.status.completed
}

ServiceRequest.status.revoked : Geannuleerd
ServiceRequest.status.enteredinerror: Weigering





@enduml