@startuml
hide circle

BeReferralPrescription <|-- BeNursingPrescription
BeNursingPrescription <|-- BeNursingMedicationPrescription
BeNursingPrescription <|-- BeNursingOtherPrescription

class BeReferralPrescription{
  |_identifier 0..*  "An identifier for the ReferralPrescription, e.g. the UHMEP identifier, once available"
  |_status 1..1  "Current status"
  |_reasonCurrentStatus 1..1  "Reason current status"
  |_authoredOn 1..1  "When this prescription was created"
  |_prescriber 1..1 Reference  "The prescribing healthcare party"
  |_co-prescriber 0..* BackboneElement  "Information about co prescribers"
  |_co-prescriber.co-prescriber 1..1 Reference  "The co-prescriber party"
  |_co-prescriber.co-prescriberSubstitute 0..1 Reference "NIHDI of co prescriber substitute party"
  |_co-prescriber.status 1..1  "Status of co prescribing status (to sign, signed or refused)"
  |_patient 1..1 Reference  "The SSIN of the person for which the referral is prescribed."
  |_originalRequest 0..1 Reference "The original request or prescription that is the reason for this request - for example when a detailed request is created by a broader request."
  |_reason 0..* Reference "The problem (code or reference) that is the main reason for this prescription"
  |_intendedProvider 0..* BackboneElement "The intended provider, i.e. who is expected to perform the procedure - a specific person or a speciality"
  |_intendedProvider.provider 0..* Reference "A reference to the provider party (e.g. a NIHDI number for a healthcare professional, a SSIN or only a displaystring for a non professional caregiver,...)"
  |_intendedProvider.discipline 1..1  "The required discipline of the provider party"
  |_validityPeriod 1..1  "Period of validity of prescription"
  |_executionPeriod 0..1  "When this prescription is executed, available after start of execution"
  |_prescribedService 1..1  "What is prescribed"
  |_resultReceiver 0..* Reference "Parties that shall be informed of the results of the prescription other then the prescriber."
  |_note 0..1 Annotation  "Additional text notes about the request."
}

class BeNursingPrescription{
  |_phoneAvailablityPrescriber 0..1 BackboneElement 
  |_phoneAvailablityPrescriber.contactPoint 0..* ContactPoint 
  |_phoneAvailablityPrescriber.availability 0..* BackboneElement 
  |_phoneAvailablityPrescriber.availability.untilHour 0..1 BackboneElement 
  |_phoneAvailablityPrescriber.availability.fromHour 0..1 BackboneElement 
  |_phoneAvailablityPrescriber.availability.weekDay 1..1 string 
  |_feedbackAsked 0..1 BackboneElement 
  |_feedbackAsked.timingFeedback 1..1 code 
  |_signature 0..1 Signature 
  |_stampOrIdentification 0..1 code "What is this?" "What is this?"
  |_mainNursingCare 1..1 CodeableConcept  "A high level code to describe the nursing care"
  |_detailedCare 0..* CodeableConcept  "Detailed code describing the nursing care demanded"
  |_bodySite 0..* CodeableConcept "When needed bodySite SHALL be given" "When needed bodySite SHALL be given"
  |_asNeeded 0..1
  |_occurence 0..1
}

class BeNursingMedicationPrescription{
  |_medication 1..1
  |_dosisInstruction 0..1
}

class BeNursingOtherPrescription{

}

@enduml