@startuml
BeReferralPrescription <|-- BeNursingPrescription
BeReferralPrescription <|-- BeDiagnosticImagingPrescription	
BeReferralPrescription <|-- BeLaboratoryPrescription
BeReferralPrescription <|-- BePhysiotherapyPrescription

class BeNursingPrescriptionGenMedication

abstract class BeReferralPrescription

BeReferralPrescription : UHMEP identifier



@enduml
