canonical: https://www.ehealth.fgov.be/standards/fhir/drp
url: https://www.ehealth.fgov.be/standards/fhir/drp
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: hl7.fhir.be.drp
name: Digital Referral Prescription
title: Digital Referral Prescription Implementation Guide
description: Digital Referral Prescription Implementation Guide
status: active
date: 2025-09-26
version: 1.0.0
copyrightYear: 2022+
releaseLabel: STU
jurisdiction: urn:iso:std:iso:3166#BE "Belgium"
dependencies:
  hl7.fhir.be.core: 2.1.2
  #hl7.fhir.be.medication: 1.0.0
  hl7.fhir.be.core-clinical: 1.0.0
  #hl7.fhir.be.allergy: 1.1.0
  hl7.fhir.extensions.r4: 4.0.1
  hl7.fhir.uv.xver-r5.r4: 0.1.0
  hl7.fhir.be.infsec: 1.2.0
  

# The publisher can be a single item or a list, each with a name and
# optional url and/or email. The first publisher's name will be used
# as IG.publisher.  The contact details and/or additional publishers
# will be translated into IG.contact values.
publisher:
  name: eHealth Platform 
  url: https://www.ehealth.fgov.be/standards/fhir
  email: support@be-ehealth-standards.atlassian.net

# ContactDetail is required by the template.
contact:
  - name: Message Structure eHealth
    telecom:
      - system: email
        value: support@be-ehealth-standards.atlassian.net
        use: work

# The pages property corresponds to IG.definition.page. SUSHI can
# auto-generate the page list, but if the author includes pages in
# this file, it is assumed that the author will fully manage the
# pages section and SUSHI will not generate any page entries.
# The page file name is used as the key. If title is not provided,
# then the title will be generated from the file name.  If a
# generation value is not provided, it will be inferred from the
# file name extension.  Any subproperties that are valid filenames
# with supported extensions (e.g., .md/.xml) will be treated as
# sub-pages.
pages:
  index.md:
    title: Home
  guidance.md:
  changes.md:
  downloads.xml:
  
# The ImplementationGuide resource defines several other properties
# not represented above. These properties can be used as-is and
# should follow the format defined in ImplementationGuide:
# * meta
# * implicitRules
# * language
# * text
# * contained
# * extension
# * modifierExtension
# * experimental
# * useContext
# * copyright
# * packageId

# The menu property will be used to generate the input/menu.xml file.
# The menu is represented as a simple structure where the YAML key
# is the menu item name and the value is the URL. The IG publisher
# currently only supports one level deep on sub-menus.
# To provide a custom menu.xml file, do not include this property and
# include a `menu.xml` file in input/includes.
menu:
  Home: index.html
  Guidance: guidance.html
  Artifacts: artifacts.html
  Downloads: downloads.html
  Changes: changes.html
  History: https://www.ehealth.fgov.be/standards/fhir/drp/history.html


parameters:
  shownav: 'true'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  path-expansion-params: Parameters-terminology-expansion.json
  pin-canonicals: pin-multiples
  path-history: https://www.ehealth.fgov.be/standards/fhir/drp/history.html
  special-url-base: https://www.ehealth.fgov.be/standards/fhir/terminology
