Logical: BeModelNursingPrescription
Parent: BeModelReferralPrescription
* ^extension[http://hl7.org/fhir/tools/StructureDefinition/logical-target].valueBoolean = true
//* Id 1..1 Identifier "UUID (see Doc : https://docs.google.com/document/d/13qamEPfdQ2HgUiXmjwHQNchpEU3LsQHF5MN9jKufX2g/edit?usp=sharing )" "UUID (see Doc : https://docs.google.com/document/d/13qamEPfdQ2HgUiXmjwHQNchpEU3LsQHF5MN9jKufX2g/edit?usp=sharing )"
//* ShortCode 1..1 Identifier "“Business” code allowing the healthcare professional to find a prescription associated with a patient" "“Business” code allowing the healthcare professional to find a prescription associated with a patient"
//* RecordedDate 1..1 dateTime "Date of encoding of the information by the Recorder." "Date of encoding of the information by the Recorder."
//* CreationDate 1..1 dateTime "Creation date of the referral prescription. This date will not change throughout the process. This date corresponds to the first recordedDate recorded for this referral prescription." "Creation date of the referral prescription. This date will not change throughout the process. This date corresponds to the first recordedDate recorded for this referral prescription."
//* Patient 1..1 Identifier "The unique identifier must be: NISS, National Registry Number or Patient Bis" "The unique identifier must be: NISS, National Registry Number or Patient Bis"
//* Author 1..1 Identifier "Reference to the healthcare professional who created the request (foreign key)." "Reference to the healthcare professional who created the request (foreign key)."
//* Status 1..1 CodeableConcept "Current status of the request (e.g. \"Active\", \"Expired\", \"Completed\", \"Cancelled\")." "Current status of the request (e.g. \"Active\", \"Expired\", \"Completed\", \"Cancelled\")."
//* StatusReason 0..1 CodeableConcept "Reason explaining the current status." "Reason explaining the current status."
//* CareRequested 1..1 CodeableConcept "Type of care requested (e.g. \"Compression therapy\", \"Sample collection\", ...)." "Type of care requested (e.g. \"Compression therapy\", \"Sample collection\", ...)."
//* Discipline 1..1 CodeableConcept "Category of care requested: here, Nurse" "Category of care requested: here, Nurse"
//* Description 0..* CodeableConcept "Additional details on the care requested" "Additional details on the care requested"
//* Type 1..1 CodeableConcept "Type of request or prescription (\"Prescription\" or \"Proposal\")." "Type of request or prescription (\"Prescription\" or \"Proposal\")."
//* OriginRequestId 0..1 Identifier "Reference to the original request ID (useful when the request is an extension of another one)." "Reference to the original request ID (useful when the request is an extension of another one)."
//* ValidationStartDate 1..1 dateTime "Start date of the prescription validity (encoded by the prescriber)." "Start date of the prescription validity (encoded by the prescriber)."
//* ValidationEndDate 1..1 dateTime "End date of the prescription validity (encoded by the prescriber)." "End date of the prescription validity (encoded by the prescriber)."
//* Problem 0..* CodeableConcept "Medical problem or clinical context related to this request (for example: \"Open wound\")." "Medical problem or clinical context related to this request (for example: \"Open wound\")."
* FeedbackNeeded 1..1 boolean "Follow-up indicator (boolean) specifying whether a feedback is expected from the doctor on this treatment." "Follow-up indicator (boolean) specifying whether a feedback is expected from the doctor on this treatment."
//* BodyLocation 0..* CodeableConcept "Anatomical location where the treatment should be applied (for example: \"Left arm\")." "Anatomical location where the treatment should be applied (for example: \"Left arm\")."
* GeneralRemarks 0..* Annotation "General remarks concerning the treatment or request." "General remarks concerning the treatment or request."
* ContraIndications 0..1 Annotation "Medical contraindications (e.g. \"Latex allergy\"). 103306004 : \"Contraindication to (x)\"" "Medical contraindications (e.g. \"Latex allergy\"). 103306004 : \"Contraindication to (x)\""
* MedicalReason 0..1 Annotation "Medical reasons for the prescription (e.g. \"Infected wound requiring follow-up\"). 410666004 : \"Reason For (x)\"" "Medical reasons for the prescription (e.g. \"Infected wound requiring follow-up\"). 410666004 : \"Reason For (x)\""